## filtri e file

genero array casuale e poi lo filtro

In [1]:
import numpy as np
n = np.random.randint(0,100, 10)
print(n)

#alternativa con shuffle
from random import shuffle
n2 = np.arange(0,10)
np.random.shuffle(n2)
print(n2)

[38 13 38 47 85 83 71 17 24 67]
[3 8 6 1 2 0 4 9 7 5]


filtri

In [2]:
nf = n[n < 50]
print(nf)

[38 13 38 47 17 24]


In [3]:
nf = n[n == 50]
print(nf)

nf = n[n != 50]
print(nf)

nf = n[n >= 75]
print(nf)

[]
[38 13 38 47 85 83 71 17 24 67]
[85 83]


posso selezionare anche i pari!

In [4]:
nf = n[n%2 == 0]
print(nf)

[38 38 24]


posso comporre filtri con operatori and e or

In [5]:
nf = n[(n > 25) & (n < 75) ]
print(nf)

nf = n[(n < 25) | (n > 75) ]
print(nf)


[38 38 47 71 67]
[13 85 83 17 24]


In [6]:
nn = np.where((n%2 == 0), "P", "D")
print(nn)

['P' 'D' 'P' 'D' 'D' 'D' 'D' 'D' 'P' 'D']


Se non passo i valori da sostituire ottengo una lista con le posizioni dei valori.

In [7]:
nn = np.where((n%2 == 0))
print(nn)

(array([0, 2, 8], dtype=int64),)


## Arrotondamenti


In [8]:
v = np.random.random(10)
v *= 10.0
print(v)

[8.84683897 2.79425574 1.98615207 2.80316176 8.33167026 0.92186404
 4.55401512 0.36785151 9.86048913 6.4889662 ]


In [9]:
np.around(v, 2)

array([8.85, 2.79, 1.99, 2.8 , 8.33, 0.92, 4.55, 0.37, 9.86, 6.49])

In [10]:
np.ceil(v)

array([ 9.,  3.,  2.,  3.,  9.,  1.,  5.,  1., 10.,  7.])

In [11]:
np.floor(v)

array([8., 2., 1., 2., 8., 0., 4., 0., 9., 6.])